Update overviewpage.cpp
RavenProject/Ravencoin pull request #867
Opened 2021-01-18 00:29 UTC by corviato1

Change cloudflare-ipfs.com to ipfs.io [line 525 & 702] because cloudflare sucks, and will not allow Ravencore to maximize IPFS video file potential

2021-02-12 21:19 UTC, TronBlack approved these changes

2021-03-10 13:32 UTC, jeroz1 approved these changes

2021-03-10 13:45 UTC, jeroz1 requested changes
I recommend pushing this to develop and not directly to master.

2021-03-10 14:58 UTC, ROSHiix approved these changes

2021-03-10 15:01 UTC, merged